language: bash

matrix:
  include:
    - os: linux
    - os: osx
      env: HOMEBREW_NO_AUTO_UPDATE=1

addons:
  apt:
    packages:
      - groff
      - shunit2

sudo: required

before_install:
  - if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then brew install bash; fi
  - if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then export PATH=/usr/local/bin:$PATH; fi
  - if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then bash -c 'echo $BASH_VERSION'; fi
  - if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then brew install shunit2; fi

before_script:
  - groff --version
  - if [[ "$TRAVIS_OS_NAME" != 'osx' ]]; then sed --version; fi

script:
  - make test
  - sudo make install
  - pipes.sh -v
  - sudo make uninstall
  - make pipes.sh.6.html
